apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myhero-ui
spec:
  hosts:
  - "ui.burstserial.com"
  gateways:
  - myhero-gateway
  http:
  - route:
    - destination:
        host: myhero-ui.myhero.svc.cluster.local
        subset: v1
      weight: 50
    - destination:
        host: myhero-ui.myhero.svc.cluster.local
        subset: v3
      weight: 50
